# Generated by Django 4.2.7 on 2023-12-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate_stars',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание к фильму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=40, message='Длительность фильма должна быть не менее 30 мин')], verbose_name='Длительность фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
