# Generated by Django 4.2.7 on 2023-12-10 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_rate_stars_alter_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=40, message='Duration must be more than 30 minutes')], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
